version: '3'
services:
  db:
    image: postgres:14.3
    restart: always
    container_name: calidad_db
    hostname: myhost
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

      